site_name: Zarinit routers
repo_url: https://github.com/zarinit-routers/docs
repo_name: GitHub
edit_uri: blob/main/docs/
copyright: Death to &copy;

site_description: Documentation for Zarinit routers
site_author: Katy248

plugins:
  - search
  - git-revision-date

theme:
  name: terminal
  palette: gruvbox_dark
  features:
    - navigation.side.indexes
    - revision.date
    - revision.history
    - footer.prev_next

extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/highlight.min.js
  - https://unpkg.com/highlightjs-cobol/dist/cobol.min.js
  # - add_hljs_highlight.js

extra_css:
  - https://cdnjs.cloudflare.com/ajax/libs/highlight.js/11.11.0/styles/a11y-dark.min.css
